image: node:18

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
     
cache:
  paths:
    - node_modules/
    - labellingTool/node_modules

pages:
  rules:
    - if: $CI_COMMIT_BRANCH == "deployment/labelling_tool"
  script:
    - cd labellingTool/
    - npm install
    - npm run build
  artifacts:
    paths:
      - labellingTool/build

