data:
  model_name: "all-mpnet-base-v2" # model name for the embeddings
  dim_reduction: "tsne" # optional if reduction of dimensionality is needed
  n_components: 2 # optional if reduction of dimensionality is needed
clustering:
  use_reduced_embeddings: False # whether to cluster on reduced or original embeddings
  algorithm: "agglomerative" # options are: kmeans, agglomerative, community_detection
  metric: "cosine" # options are: euclidean, cosine
  linkage: "average" # only for agglom, options are: ward, complete, average, single
  n_clusters:
    - 1000
  # distance_thresholds: # only for agglom and community detection, will be ignored if n_clusters is not None
  #   - 0.5
evaluation:
  save_to_disk: True # whether to save the evaluation results to disk
  merge_duplicates: True # whether to merge duplicated usage options before saving
