model: "t5-small"
artifact:
  name: #"scintillating-mandu-99"
  checkpoint: #9
epochs: 1
batch_size: 8
optimizer: 
  name: "AdamW"
  learning_rate: 0.01
  weight_decay: 0.01
dataset:
  version: "corrected_merge"
  validation_split: 0.10
cluster:
  devices: 1 #Number of gpus per node
  num_nodes: 1 #Number of nodes
