# further configuration can be looked up here: https://huggingface.co/docs/transformers/v4.26.1/en/main_classes/text_generation#transformers.GenerationConfig
do_sample: False
temperature: 1.0
top_p: 1.0
num_beams: 4
repetition_penalty: 1.2
length_penalty: 1.0
num_beam_groups: 1
max_new_tokens: 512
