model_name: "RWKV"
active_layers:
  encoder: "-3:" # use python slice syntax (e.g. ':0' for no layers and ':' for all)
  decoder: "-3:"
  lm_head: True
gradual_unfreezing_mode: "" # "module speed" for each module (seperated by comma) with module=[decoder, encoder], speed int NOT 0
artifact:
  name: #"scintillating-mandu-99"
  checkpoint: #9
epochs: 10
batch_size: 1
accumulate_grad_batches: 8
optimizer: #Set all parameters you do not want to null
  name: "AdamW"
  weight_decay: 0.01
  scale_parameter: False
  relative_step: False
  warmup_init: null
  lr: 0.0001
lr_scheduler_type: OneCycleLR #Currently supports OneCycleLR and AdaFactor. If you do not want a LR scheduler write null
dataset:
  version: "pipeline-test-new"
  validation_split: 0.10
cluster:
  devices: 1 #Number of gpus per node
  num_nodes: 1 #Number of nodes
test_run: True
multiple_usage_options_strategy: "default"
prompt_id: "original"
seed: 42 # can be left empty

# Options for 'multiple_usage_options_strategy':
#   - "default" -> wie gehabt kommt ein Datapoint raus, der alle usage options in gegebener Reihenfolge enthält
#   - "flat" -> ein Datapoint für jede usage option
#   - "shuffle" -> wie bei "default" ein Datapoint, aber mit zufälliger Reihenfolge
#   - "shuffle-n" -> n zufällige Datapoints mit jeweils unterschiedlichen zufälligen Permutationen
#   - "shuffle-all" -> alle Permutationen als separate Datapoints

# Further examples for 'active_layers' syntax:
#   - ':0' -> activate none
#   - ':' -> activate all ('0:') also works
#   - '-5:' -> activate last five
#   - ':3' -> activate first three
