model: "t5-small"
active_layers: "encoder_0 decoder_0 lm_head" #Space seperated components, with number of layers backwards after _. E.g. "encoder_1 decoder_2 lm_head"
artifact:
  name: #"scintillating-mandu-99"
  checkpoint: #9
epochs: 50
batch_size: 8
optimizer:
  name: "AdamW"
  weight_decay: 0.01
max_lr: 0.001
dataset:
  version: "purple-frog-69"
  validation_split: 0.10
cluster:
  devices: 1 #Number of gpus per node
  num_nodes: 1 #Number of nodes
test_run: False
